TimeCardsApp/ETT.Client/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ETT.Web.Models;
using ETT.Web.Models.Users;
using ETT.Web.Util.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ETT.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : AppBaseController
    {
        RoleManager<Role> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<Role> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.OrderBy(x => x.Name).ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                if (_roleManager.Roles.Any(x => x.Name == name))
                {
                    ModelState.AddModelError(string.Empty, "Данная роль содержиться в базе");
                    return View("Create", name);
                }

                IdentityResult result = await _roleManager.CreateAsync(new Role(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View("Create", name);
        }

        [HttpGet]
        public IActionResult Delete(DeleteRoleViewModel deleteRoleViewModel)
        {
            return View(deleteRoleViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            Role role = await _roleManager.FindByIdIntAsync(id);
            if (role.NormalizedName.CompareTo("ADMIN") == 0)
            {
                return RedirectToAction("Index");
            }
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UserList(int page = 1, string PageFilter = "")
        {
            int pageSize = 5;

            IQueryable<User> users = null;
            if (!String.IsNullOrEmpty(PageFilter))
            {
                users = _userManager.Users.Where(x => x.Email.Contains(PageFilter));
            }
            else
            {
                users = _userManager.Users;
            }

            var count = await users.CountAsync();
            var items = await users.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            RolesUsersListViewModel viewModel = new RolesUsersListViewModel
            {
                PageViewModel = pageViewModel,
                Users = items,
                FilterName = PageFilter
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int userId, int page, string filter)
        {
            User user = await _userManager.FindByIdIntAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles,
                    PageNumber = page,
                    FilterString = filter
                };
                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int userId, List<string> roles, int page, string PageFilter)
        {
            User user = await _userManager.FindByIdIntAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                IdentityResult resultAdd = await _userManager.AddToRolesNVAsync(user, addedRoles);

                IdentityResult resultRemove = await _userManager.RemoveFromRolesNVAsync(user, removedRoles);

                return RedirectToAction("UserList", new { page = page, PageFilter = PageFilter });
            }

            return NotFound();
        }
    }
}

TimeCardsApp/ETT.Client/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ETT.Web.Models.Users;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ETT.Web.Util.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using ETT.Web.Models;
using ETT.Web.Infrastructure;
using ETT.Logic.Interfaces;
using ETT.Logic.Services;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Newtonsoft.Json;
using ETT.Logic.DTO;

namespace ETT.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class UsersController : AppBaseController
    {
        private readonly UserManager<User> _userManager;
        private readonly IFileService _fileService;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IUserService _userService;

        public UsersController(UserManager<User> userManager,
            IFileService fileService,
            IHostingEnvironment hostingEnvironment,
            IUserService userService)
        {
            _userManager = userManager;
            _fileService = fileService;
            _hostingEnvironment = hostingEnvironment;
            _userService = userService;
        }

        public async Task<IActionResult> Index(int page = 1, string PageFilter = "")
        {
            int pageSize = 5;

            IQueryable<User> users = null;
            if (!String.IsNullOrEmpty(PageFilter))
            {
                users = _userManager.Users.Where(x => x.Email.Contains(PageFilter));
            }
            else
            {
                users = _userManager.Users;
            }

            var count = await users.CountAsync();
            var items = await users.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            UsersIndexViewModel viewModel = new UsersIndexViewModel
            {
                PageViewModel = pageViewModel,
                Users = items,
                FilterName = PageFilter
            };

            return View(viewModel);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    //adding user role
                    await _userManager.AddToRoleAsync(user, "user");
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            // check
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            //EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email };
            EditUserViewModel model = Mappers.MapUserToUserEditVM(user);
            model.AvatarPath = _fileService.GetAvatarPath(user.Id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                UserDTO userDTO = Mappers.MapUserEditVMToUserDTOEditVM(model);

                _userService.UpdateUserAccountData(userDTO);

                return RedirectToAction("Index");
                //User user = await _userManager.FindByIdIntAsync(model.Id);

                //if (userDTO != null)
                //{

                //    //if (model.Email.CompareTo(user.Email) == 0) return RedirectToAction("Index");
                //    //user.Email = model.Email;
                //    //user.UserName = model.Email;

                //    //var result = await _userManager.UpdateAsync(user);
                //    //if (result.Succeeded)
                //    //{
                //    //    return RedirectToAction("Index");
                //    //}
                //    //else
                //    //{
                //    //    foreach (var error in result.Errors)
                //    //    {
                //    //        ModelState.AddModelError(string.Empty, error.Description);
                //    //    }
                //    //}
                //}
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id, bool confirm = false)
        {
            User user = await _userManager.FindByIdIntAsync(id);

            if (user != null)
            {
                if (confirm)
                {
                    if (user.NormalizedUserName == "ad1min@mail.com".ToUpper())
                    {
                        return RedirectToAction("Index");
                    }

                    IdentityResult result = await _userManager.DeleteAsync(user);
                }
                else
                {
                    ViewBag.Id = id;
                    ViewBag.Name = user.UserName;
                    return View();
                }

            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdIntAsync(model.Id);
                if (user != null)
                {
                    IdentityResult result =
                        await _userManager.ChangePasswordNVAsync(user, model.OldPassword, model.NewPassword);


                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveIMG()
        {
            try
            {
                MemoryStream stream = new MemoryStream();
                Request.Body.CopyTo(stream);
                stream.Position = 0;
                string id = "";
                using (StreamReader reader = new StreamReader(stream))
                {
                    string requestBody = reader.ReadToEnd();
                    if (requestBody.Length > 0)
                    {
                        var obj = JsonConvert.DeserializeObject<PostData>(requestBody);
                        if (obj != null)
                        {
                            id = obj.id;
                        }
                    }

                }
                _fileService.RemoveAvatarImage(int.Parse(id), _hostingEnvironment.WebRootPath);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json("complete");
        }

        public class PostData
        {
            public string id { get; set; }
        }
    }
}

TimeCardsApp/ETT.Client/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Properties.Logo</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/materialize/dist/css/materialize.css" />
        <link rel="stylesheet" href="~/css/materialize.fix.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css"
              asp-fallback-href="~/lib/materialize/dist/css/materialize.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="@Design.ColorAdmin">
        <div class="container nav-wrapper">
            <div class="col s12">
                @if (IsSectionDefined("breadcrumbs"))
                {
                    @RenderSection("breadcrumbs")
                }
                else { }
                <a asp-controller="Users" asp-action="Index" class="adminnavlinks">
                    <i class="@*hide-on-large-only*@ material-icons left"></i>
                    <span class="@*hide-on-med-and-down*@">Users</span>
                </a>
                <a asp-controller="Roles" asp-action="Index" class="adminnavlinks">
                    <i class="@*hide-on-large-only*@ material-icons left"></i>
                    <span class="@*hide-on-med-and-down*@">Roles</span>
                </a>
                <a asp-controller="Home" asp-action="Index" class="adminnavlinks right">
                    <i class="@*hide-on-large-only*@ material-icons left"></i>
                    <span class="@*hide-on-med-and-down*@">Go Home</span>
                </a>
            </div>
        </div>
    </nav>
    <main>
        @RenderBody()
    </main>
    <footer class="page-footer @Design.ColorAdmin">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Footer Content</h5>
                    <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
                </div>
                <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Links</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                &copy; @DateTime.UtcNow.Year All rights reserved.
                <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/materialize/dist/js/materialize.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"
                asp-fallback-src="~/lib/materialize/dist/js/materialize.min.js">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

TimeCardsApp/ETT.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Properties.Logo</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/materialize/dist/css/materialize.css" />
        <link rel="stylesheet" href="~/css/materialize.fix.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"
              asp-fallback-href="~/lib/materialize/dist/css/materialize.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="@Design.Color">
        <div class="container nav-wrapper">
            <a asp-controller="Home" asp-action="Index" class="brand-logo left"><i class="material-icons">access_time</i>@Properties.Logo</a>
            <ul class="right">
                @*
                    <li>
                        <a asp-controller="Home" asp-action="Index">
                            <i class="hide-on-large-only material-icons">home</i>
                            <span class="hide-on-med-and-down">Home</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="About">
                            <i class="hide-on-large-only material-icons">info_outline</i>
                            <span class="hide-on-med-and-down">About</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="Contact">
                            <i class="hide-on-large-only material-icons">contacts</i>
                            <span class="hide-on-med-and-down">Contact</span>
                        </a>
                    </li>
                *@
                @if (User.Identity.IsAuthenticated)
                {
                    <li>
                        <a asp-area="" asp-controller="Record" asp-action="Create">
                            <i class="hide-on-large-only material-icons">add_circle</i>
                            <span class="hide-on-med-and-down">@Localizer["RecordLink"]</span>
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Record" asp-action="UserList">
                            <i class="hide-on-large-only material-icons">dehaze</i>
                            <span class="hide-on-med-and-down">@Localizer["MyRecordsLink"]</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Project" asp-action="List">
                            <i class="hide-on-large-only material-icons">list</i>
                            <span class="hide-on-med-and-down">@Localizer["ProjectsLink"]</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Report" asp-action="CreateReport">
                            <i class="hide-on-large-only material-icons">assessment</i>
                            <span class="hide-on-med-and-down">@Localizer["ReportsLink"]</span>
                        </a>
                    </li>
                }
                <li>
                    <a asp-controller="" asp-action="" data-activates="dropdown" data-beloworigin="true" class="dropdown-button">
                        <i class="material-icons left">account_box</i>
                        <span class="white-text hide-on-med-and-down">
                            @(User.Identity.IsAuthenticated ? @User.Identity.Name : Localizer["AccountLink"].Value)
                        </span>
                        <i class="material-icons right">arrow_drop_down</i>
                    </a>
                </li>
                <li>
                    <a asp-controller="" asp-action="" data-activates="dropdownLanguage" data-beloworigin="true" class="dropdown-button" style="padding-left:40px;padding-right:40px">
                        <span>&nbsp</span>
                        <i class="material-icons right" style="margin-left:-5px">language</i>
                    </a>
                </li>
            </ul>
        </div>

        <!-- Dropdown Structure -->
        <ul id="dropdown" class="dropdown-content collection">
            @if (User.Identity.IsAuthenticated)
            {
                <li>
                    <a asp-controller="Account" asp-action="Update" asp-route-name="@User.Identity.Name">
                        <i class="material-icons">person</i>@Localizer["ProfileLink"]
                    </a>
                </li>
                <li>
                    <a asp-controller="Account" asp-action="ChangePassword" asp-route-name="@User.Identity.Name">
                        <i class="material-icons">local_parking</i>@Localizer["PasswordLink"]
                    </a>
                </li>
                @if (User.IsInRole("admin"))
                {
                    <li><a asp-controller="Users" asp-action="Index"><i class="material-icons left">vpn_key</i>@Localizer["AdminLink"]</a></li>
                }
                <li><a asp-controller="Account" asp-action="LogOff"><i class="material-icons left">person_outline</i>@Localizer["LogoutLink"]</a></li>
            }
            else
            {
                <li><a asp-controller="Account" asp-action="Register"><i class="material-icons">person_add</i>@Localizer["RegisterLink"]</a></li>
                <li><a asp-controller="Account" asp-action="Login"><i class="material-icons">done</i>@Localizer["LoginLink"]</a></li>
            }
        </ul>
        <!-- Dropdown Structure Language -->
        <ul id="dropdownLanguage" class="dropdown-content collection">
            <li>
                <a asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"  asp-route-query="@Context.Request.QueryString" asp-route-culture="ru">
                    Rus
                </a>
            </li>
            <li>
                <a asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" asp-route-query="@Context.Request.QueryString" asp-route-culture="en">
                    Eng
                </a>
            </li>
        </ul>
    </nav>

    <main>
        @RenderBody()
    </main>

    <footer class="page-footer @Design.Color">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Footer Content</h5>
                    <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
                </div>
                <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Links</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                &copy; @DateTime.UtcNow.Year All rights reserved.
                <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/materialize/dist/js/materialize.js"></script>
        <script src="~/js/functions.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"
                asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"
                asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"
                asp-fallback-src="~/lib/materialize/dist/js/materialize.min.js">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>