TimeCardsApp/ETT.Client/Models/Projects/ListViewModel.cs
using System.Collections.Generic;

namespace ETT.Web.Models.Projects
{
    public class ListViewModel
    {
        public IEnumerable<ProjectViewModel> Projects { get; set; }
    }
}

TimeCardsApp/ETT.Client/Models/Projects/Task/ListViewModel.cs
using System.Collections.Generic;

namespace ETT.Web.Models.Projects.Task
{
    public class ListViewModel
    {
        public int projectId { get; set; }
        public bool Manager { get; set; }

        public IEnumerable<TaskViewModel> Tasks { get; set; }
    }
}

TimeCardsApp/ETT.Client/Models/Projects/User/ListViewModel.cs
using ETT.Utils.Enums;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ETT.Web.Models.Projects.User
{
    public class ListViewModel
    {
        public int ProjectId { get; set; }
        public bool Admin { get; set; }

        public IEnumerable<UserViewModel> Users { get; set; }
        public IEnumerable<ProjectRole> Roles { get; } = Enum.GetValues(typeof(ProjectRole)).Cast<ProjectRole>();
    }
}

TimeCardsApp/ETT.Client/Models/Record/ProjectRecordViewModel.cs
using ETT.Logic.DTO.Projects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ETT.Web.Models.Record
{
    public class ProjectRecordViewModel:RecordViewModel
    {
        public IEnumerable<ProjectDTO> Projects { get; set; }
        public IEnumerable<ProjectTaskDTO> Tasks { get; set; }
    }
}

TimeCardsApp/ETT.Client/Models/Record/RecordListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ETT.Web.Models.Record
{
    public class RecordListViewModel
    {
        public IEnumerable<RecordViewModel> Records { get; set; } 
    }
}

TimeCardsApp/ETT.Client/Models/Record/RecordViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace ETT.Web.Models.Record
{
    public class RecordViewModel
    {
        public int Id { get; set; }
        public int UserId { get; set; }

        [Display(Name = "Hours")]
        [Range(0.1,15,ErrorMessage = "WorkTime")]
        [Required(ErrorMessage = "RequiredHours")]
        public double Hours { get; set; }
       
        [Display(Name = "Note")]
        [MinLength(3,ErrorMessage ="MinLengthNote")]
        [Required(ErrorMessage ="RequiredNote")]
        public string Note { get; set; }

        [Display(Name = "StartDate")]
        [Required(ErrorMessage = "RequiredStartDate")]
        public string Date { get; set; }

        [Display(Name = "StartTime")]
        [Required(ErrorMessage = "RequiredStartTime")]
        public string Time { get; set; }

        [Display(Name = "CreationTime")]
        public DateTime RecordDateTime { get; set; }

        [RegularExpression(@"[1-9][0-9]{0,}",ErrorMessage = "RequeredProjectName")]
        [Display(Name = "ProjectName")]
        public int ProjectId { get; set; }

        [Display(Name = "Project Name")]
        public string ProjectName { get; set; }

        [RegularExpression(@"[1-9][0-9]{0,}", ErrorMessage = "RequeredTaskName")]
        [Display(Name = "TaskName")]
        public int TaskId { get; set; }

        [Display(Name = "Task Name")]
        public string TaskName { get; set; }
    }
}

TimeCardsApp/ETT.Client/Models/Record/SortState.cs
public enum SortState
{
    IdAsc,
    IdDesc,
    UserIdAsc,
    UserIdDesc,
    UserNameAsc,
    UserNameDesc,
    ProjectNameAsc,   
    ProjectNameDesc,   
    TaskNameAsc,
    TaskNameDesc,
    NoteAsc,
    NoteDesc,
    HourAsc,
    HourDesc,
    DataTimeAsc,
    DataTimeDesc
}

TimeCardsApp/ETT.Client/Controllers/RecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using ETT.Logic.DTO;
using ETT.Logic.Interfaces;
using ETT.Logic.Services;
using ETT.Utils.Logger;
using ETT.Web.Models.Record;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ETT.Web.Util.Reporting;
using ETT.Logic.DTO.Projects;
using Microsoft.Extensions.Localization;
using ETT.Utils.Enums;
using System.Globalization;

namespace ETT.Web.Controllers
{
    public class RecordController : Controller
    {
        private IRecordService service;
        private IUserService users;
        private IProjectService projects;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        // Dependency injection
        public RecordController(IRecordService recordService, IUserService userService, IProjectService projectService,
                   IStringLocalizer<SharedResource> sharedLocalizer)
        {
            this.service = recordService;
            this.users = userService;
            this.projects = projectService;
            _sharedLocalizer = sharedLocalizer;
        }


        public ActionResult Index()
        {
            return RedirectToAction(nameof(List));
        }

        [HttpPost]
        public ActionResult PdfWriter(IEnumerable<RecordViewModel> records)
        {
            ToPDF pdfwriter = new ToPDF();
            pdfwriter.RecordsToPDF(records);
            return PartialView();
        }

        // GET: Record/List

        [Authorize(Roles = "admin")]
        public ActionResult List()
        {
            return View(
                new RecordListViewModel()
                {
                    Records = service.GetRecords().Select(
                        record =>
                        new RecordViewModel()
                        {
                            Id = record.Id,
                            UserId = record.UserId,
                            TaskId = record.TaskId,
                            Hours = record.Hours,
                            Note = record.Note,
                            RecordDateTime = record.RecordDateTime,
                            ProjectId = record.ProjectId
                        }
                    )
                }
            );
        }
        // sort Action
        public RecordListViewModel SortBy(SortState sortParam, IEnumerable<RecordViewModel> records)
        {
            RecordListViewModel model = new RecordListViewModel();
            switch (sortParam)
            {
                case SortState.IdAsc:
                    {
                        model.Records = records.OrderBy(s => s.Id);
                        break;
                    }
                case SortState.IdDesc:
                    {
                        model.Records = records.OrderByDescending(s => s.Id);
                        break;
                    }
                case SortState.UserIdAsc:
                    {
                        model.Records = records.OrderBy(s => s.UserId);
                        break;
                    }
                case SortState.UserIdDesc:
                    {
                        model.Records = records.OrderByDescending(s => s.UserId);
                        break;
                    }
                case SortState.ProjectNameAsc:
                    {
                        model.Records = records.OrderBy(s => s.ProjectName);
                        break;
                    }
                case SortState.ProjectNameDesc:
                    {
                        model.Records = records.OrderByDescending(s => s.ProjectName);
                        break;
                    }
                case SortState.TaskNameAsc:
                    {
                        model.Records = records.OrderBy(s => s.TaskName);
                        break;
                    }
                case SortState.TaskNameDesc:
                    {
                        model.Records = records.OrderByDescending(s => s.TaskName);
                        break;
                    }
                case SortState.NoteAsc:
                    {
                        model.Records = records.OrderBy(s => s.Note);
                        break;
                    }
                case SortState.NoteDesc:
                    {
                        model.Records = records.OrderByDescending(s => s.Note);
                        break;
                    }
                case SortState.HourAsc:
                    {
                        model.Records = records.OrderBy(s => s.Hours);
                        break;
                    }
                case SortState.HourDesc:
                    {
                        model.Records = records.OrderByDescending(s => s.Hours);
                        break;
                    }
                case SortState.DataTimeAsc:
                    {
                        model.Records = records.OrderBy(s => s.RecordDateTime);
                        break;
                    }
                case SortState.DataTimeDesc:
                    {
                        model.Records = records.OrderByDescending(s => s.RecordDateTime);
                        break;
                    }
                default:
                    {
                        model.Records = records.OrderBy(s => s.Id);
                        break;
                    }
            }
            return model;
        }
        // GET: Record/UserList
        public ActionResult UserList(SortState sort = SortState.IdAsc, int lastsort = 0)
        {
            int userId = users.GetUserIdByName(User.Identity.Name);
            var records = service.GetRecords().Where(record => record.UserId == userId).Select(
                  record =>
                    new RecordViewModel()
                    {
                        Id = record.Id,
                        UserId = userId,
                        ProjectId = record.ProjectId,
                        TaskId = record.TaskId,
                        TaskName = projects.GetTask(record.TaskId).Name,
                        ProjectName = projects.GetProject(record.ProjectId).Name,
                        Hours = record.Hours,
                        Note = record.Note,
                        RecordDateTime = record.RecordDateTime,
                    }
                );
            ViewData["IdSort"]          = sort == SortState.IdAsc ? SortState.IdDesc : SortState.IdAsc;
            ViewData["UserIdSort"]      = sort == SortState.UserIdAsc ? SortState.UserIdDesc : SortState.UserIdAsc;
            ViewData["ProjectNameSort"] = sort == SortState.ProjectNameAsc ? SortState.ProjectNameDesc : SortState.ProjectNameAsc;
            ViewData["TaskNameSort"]    = sort == SortState.TaskNameAsc ? SortState.TaskNameDesc : SortState.TaskNameAsc;
            ViewData["NoteSort"]        = sort == SortState.NoteAsc ? SortState.NoteDesc : SortState.NoteAsc;
            ViewData["HourSort"]        = sort == SortState.HourAsc ? SortState.HourDesc : SortState.HourAsc;
            ViewData["DataTimeSort"]    = sort == SortState.DataTimeAsc ? SortState.DataTimeDesc : SortState.DataTimeAsc;
            return View("List", SortBy(sort, records));
        }

        // GET: Record/Create
        public ActionResult Create()
        {
            int userId = users.GetUserIdByName(User.Identity.Name);
            var userProjects = projects.GetUserProjects(userId, (int)ProjectRole.Employee);
            List<ProjectTaskDTO> tasks = new List<ProjectTaskDTO>();
            foreach (var proj in userProjects)
            {
                tasks.AddRange(projects.GetTasks(proj.Id).ToList());
            }
            return View(new ProjectRecordViewModel()
            {
                Tasks = tasks,
                Projects = userProjects
            });
        }

        public ActionResult GetTaskList(int id)
        {
            int userId = users.GetUserIdByName(User.Identity.Name);
            var userProjects = projects.GetUserProjects(userId, (int)ProjectRole.Employee);
            List<ProjectTaskDTO> tasks = new List<ProjectTaskDTO>();
            tasks.AddRange(projects.GetTasks(id).ToList());
            return View(new ProjectRecordViewModel()
            {
                Tasks = tasks,
                Projects = userProjects
            });
        }
        
        // POST: Record/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProjectRecordViewModel record)
        {
            int userId = users.GetUserIdByName(User.Identity.Name);
            if (ModelState.IsValid)
            {  
                service.CreateRecord(
                    new RecordDTO()
                    {
                        UserId = userId,
                        TaskId = record.TaskId,
                        Hours = record.Hours,
                        Note = record.Note,
                        RecordDateTime = DateTime.Parse(record.Date + ',' + record.Time, new CultureInfo("ru", false)),
                        ProjectId = record.ProjectId
                    }
                );

                return RedirectToAction(nameof(UserList));
            }
            var userProjects = projects.GetUserProjects(userId, (int)ProjectRole.Employee);
            record.Projects = userProjects;
            return View(record);
        }

        // GET: Record/Edit/{id}
        public ActionResult Edit(int id)
        {
            RecordDTO record = service.GetRecord(id);
            int userId = users.GetUserIdByName(User.Identity.Name);
            return View(
                new RecordViewModel()
                {
                    Id = record.Id,
                    UserId = userId,
                    TaskId = record.TaskId,
                    Hours = record.Hours,
                    Note = record.Note,

TimeCardsApp/ETT.Client/Controllers/ReportPDFController.cs
using ETT.Web.Models.Record;
using ETT.Web.Models.Report;
using ETT.Web.Util.Reporting;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ETT.Web.Controllers
{
    public class ReportPDFController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        public ReportPDFController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        [HttpPost]
        public RedirectResult PdfRecordWriter(IEnumerable<RecordViewModel> records)
        {
            ToPDF pdfwriter = new ToPDF();
            pdfwriter.RecordsToPDF(records);
            return RedirectPermanent("/Record/UserList");
        }
        
        [HttpPost]
        public IActionResult GetExcel(IEnumerable<ReportRecordsViewModel> records)
        {
            string fileName = "Report_" + DateTime.Now.ToString("yyyy-MM-dd--hh-mm-ss") + ".xlsx";
            ToPDF pdfwriter = new ToPDF();
            var excelInst = pdfwriter.GenerateExcel(records);
            return File(excelInst.GetAsByteArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
        }
        [HttpPost]
        public IActionResult GetPdf(IEnumerable<ReportRecordsViewModel> records)
        {
            string fileName = "Report_" + DateTime.Now.ToString("yyyy-MM-dd--hh-mm-ss") + ".pdf";
            ToPDF pdfwriter = new ToPDF();
            var bytes = pdfwriter.GeneratePdf(records).ToArray();
            return File(bytes, "application/pdf", fileName);
        }
    }
}

TimeCardsApp/ETT.Client/Views/Record/Create.cshtml
@model ETT.Web.Models.Record.ProjectRecordViewModel

@{
    ViewData["Title"] = Localizer["Title"];
}

<div class="container">
    <div class="row">
        <div class="col s12 offset-l1 l10">
            <form asp-action="Create">
                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="card red lighten-3 white-text">
                        <div class="card-content">
                            <span class="card-title">@Localizer["SmthGoesWrong"]</span>
                            <div asp-validation-summary="All"></div>
                        </div>
                    </div>
                }
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">@Localizer["Title"]</span>
                        <div class="input-field" id="pickercontainer">
                            <select id="create-project-options">
                                <option value="" disabled selected>@Localizer["ChooseProject"]</option>
                                @foreach (var proj in Model.Projects)
                                {
                                    <option value="@proj.Id">@proj.Name</option>
                                }
                            </select>
                            <label asp-for="ProjectId"></label>
                            <input id="ProjId" type="hidden" asp-for="ProjectId" class="">
                        </div>
                        <input id="TaskId" type="hidden" asp-for="TaskId" class="">
                        <div id="task-selector" class="input-field">
                        </div>
                        <div class="input-field">
                            <input asp-for="Note" class="">
                            <label asp-for="Note"></label>
                            @*//<span asp-validation-for="Note"></span>*@
                        </div>
                        <div class="input-field">
                            <input asp-for="Hours" class="" />
                            <label asp-for="Hours"></label>
                           @*// <span asp-validation-for="Hours"></span>*@
                        </div>
                        <div class="input-field">
                            <label asp-for="Date"></label>
                            <input id="date" type="text" class="datepicker " asp-for="Date">
                           @*<span asp-validation-for="Date"></span>*@
                        </div>
                        <div class="input-field">
                            <label asp-for="Time"></label>
                            <input id="time" type="text" class="timepicker " asp-for="Time">
                            @*<span asp-validation-for="Time"></span>*@
                        </div>
                        <div class="">
                            <a id="pick-current-date-time" class="waves-effect waves-light btn"><i class="material-icons left">add_alarm</i>@Localizer["CurrentDateTime"]</a>
                        </div>
                    </div>
                    <div class="card-action">
                        <input id="Create-btn" type="submit" class="btn @Design.Color" value="@Localizer["Create"]" />
                        <a asp-action="UserList"><input type="button" class="btn @Design.Color " value="@Localizer["BacktoList"]" /></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(function () {
            $('.datepicker').pickadate({
                selectMonths: true, // Creates a dropdown to control month
                selectYears: 15, // Creates a dropdown of 15 years to control year,
                today: 'Today',
                clear: 'Clear',
                close: 'Ok',
                closeOnSelect: false // Close upon selecting a date,
            });
        });
        $(function () {
            $('.timepicker').pickatime({
                default: 'now', // Set default time: 'now', '1:30AM', '16:30'
                fromnow: 0,       // set default time to * milliseconds from now (using with default = 'now')
                twelvehour: false, // Use AM/PM or 24-hour format
                donetext: 'OK', // text for done-button
                cleartext: 'Clear', // text for clear-button
                canceltext: 'Cancel', // Text for cancel-button
                autoclose: false, // automatic close timepicker
                ampmclickable: true, // make AM PM clickable
                aftershow: function () { } //Function for after opening timepicker
            });
            Materialize.updateTextFields();
        });

        $(document).ready(function () {
            $('select').material_select();
        });
        $('#time').on('change', function () {
            Materialize.updateTextFields();
        });
        // Current DateTimePicker event
        $('#pick-current-date-time').on('click', function () {
            DateTimeFunction();
        });

        function DateTimeFunction() {
            var date = new Date();
            document.getElementById('date').value = date.toLocaleDateString("ru");
            document.getElementById('time').value = date.toLocaleTimeString("ru");
            Materialize.updateTextFields();
        }

        // Update task select
        $('#create-project-options').on('change', function () {
            $('#ProjId').val($(this).val());
            UpdateTaskSelect($(this).val());
        });

        function UpdateTaskSelect(number) {
            $('#task-selector').load(
                url = '/Record/GetTaskList/' + number,
                success = function (data) {
                    console.log(data);
                    $('#create-task-options').material_select();
                    $('#create-task-options').on('change', function () {
                        $('#TaskId').val($(this).val());
                    });
                }
            )
        }
    </script>
    @*<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>*@
}

TimeCardsApp/ETT.Client/Views/Record/Delete.cshtml
@model ETT.Web.Models.Record.RecordViewModel

@{
    ViewData["Title"] = Localizer["Title"];
}

<div class="container">
    <div class="row">
        <div class="col s12 offset-l1 l10">
            <div class="card">
                <div class="card-content">
                    <h4 style="margin-top: 0">@Localizer["Title"]</h4>
                    <span class="card-title">@Localizer["ConfirmQuestion"]</span>
                    <div class="row">
                        <table class="col s12 bordered vertical">
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.ProjectId)</th>
                                <td>@Html.DisplayFor(model => model.ProjectName)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.TaskId)</th>
                                <td>@Html.DisplayFor(model => model.TaskName)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Note)</th>
                                <td>@Html.DisplayFor(model => model.Note)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Hours)</th>
                                <td>@Html.DisplayFor(model => model.Hours)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.RecordDateTime)</th>
                                <td>@Html.DisplayFor(model => model.RecordDateTime)</td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="card-action">
                    <form asp-action="Delete">
                        <input type="submit" value=@Localizer["Delete"] class="btn red darken-2" />
                        <a asp-action="UserList"><input type="button" class="btn @Design.Color right" value=@Localizer["BacktoList"] /></a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

TimeCardsApp/ETT.Client/Views/Record/GetTaskList.cshtml
@model ETT.Web.Models.Record.ProjectRecordViewModel

@{
    Layout = null;
}
<select id="create-task-options">
    <option value="" disabled selected>@Localizer["ChooseTask"]</option>
    @foreach (var task in Model.Tasks)
    {
        <option value="@task.Id">@task.Name</option>
    }
</select>
<label asp-for="TaskId"></label>

TimeCardsApp/ETT.Client/Views/Record/List.cshtml
@model ETT.Web.Models.Record.RecordListViewModel

@{
    ViewData["Title"] = Localizer["Title"];
}
<div class="container">
    <div class="row">
        <h4 class="col s12">
            <span>@Localizer["Title"]</span>
            <span class="right">
                <a asp-action="Create"><input type="button" class="btn @Design.Color" value=@Localizer["Create"]></a>
            </span>
        </h4>
    </div>
    <div class="row">
        <table class="col s12 bordered highlight">
            <thead>
                <tr>
                    <th><a asp-action="UserList" asp-route-sort="@ViewData["IdSort"]">@Localizer["RecordID"]</a></th>
                    <th><a asp-action="UserList" asp-route-sort="@ViewData["ProjectNameSort"]">@Localizer["ProjectName"]</a></th>
                    <th><a asp-action="UserList" asp-route-sort="@ViewData["TaskNameSort"]">@Localizer["TaskName"]</a></th>
                    <th><a asp-action="UserList" asp-route-sort="@ViewData["NoteSort"]">@Localizer["Note"]</a></th>
                    <th><a asp-action="UserList" asp-route-sort="@ViewData["HourSort"]">@Localizer["Hours"]</a></th>
                    <th><a asp-action="UserList" asp-route-sort="@ViewData["DataTimeSort"]">@Localizer["StartDate"]</a></th>
                    <th class="right-align">@Localizer["Actions"]</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var record in Model.Records)
                {
                    <tr>
                        <td>
                            @record.Id
                        </td>
                        <td>
                            @record.ProjectName
                        </td>
                        <td>
                            @record.TaskName
                        </td>
                        <td>
                            @record.Note
                        </td>
                        <td>
                            @record.Hours
                        </td>
                        <td>
                            @record.RecordDateTime
                        </td>
                        <td>
                            <a asp-action="Delete" asp-route-id="@record.Id"><span class="new badge red darken-2" data-badge-caption="@Localizer["Delete"]"></span></a>
                            <a asp-action="Edit" asp-route-id="@record.Id"><span class="new badge orange darken-3" data-badge-caption="@Localizer["Edit"]"></span></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <form asp-controller="ReportPDF" asp-action="PdfRecordWriter" method="post">
            @for (int i = 0; i < Model.Records.Count(); i++)
            {
                <p>
                    <input type="hidden" name="records[@i].Id" value="@Model.Records.ToList()[i].Id" />
                </p>
                <p>
                    <input type="hidden" name="records[@i].UserId" value="@Model.Records.ToList()[i].UserId" />
                </p>
                <p>
                    <input type="hidden" name="records[@i].ProjectId" value="@Model.Records.ToList()[i].ProjectId" />
                </p>
                <p>
                    <input type="hidden" name="records[@i].ProjectName" value="@Model.Records.ToList()[i].ProjectName" />
                </p>
                <p>
                    <input type="hidden" name="records[@i].TaskId" value="@Model.Records.ToList()[i].TaskId" />
                </p>
                <p>
                    <input type="hidden" name="records[@i].TaskName" value="@Model.Records.ToList()[i].TaskName" />
                </p>
                <p>
                    <input type="hidden" name="records[@i].Note" value="@Model.Records.ToList()[i].Note" />
                </p>
                <p>
                    <input type="hidden" name="records[@i].Hours" value="@Model.Records.ToList()[i].Hours" />
                </p>
                <p>
                    <input type="hidden" name="records[@i].Date" value="@Model.Records.ToList()[i].Date" />
                </p>
                <p>
                    <input type="hidden" name="records[@i].Time" value="@Model.Records.ToList()[i].Time" />
                </p>
                <p>
                    <input type="hidden" name="records[@i].RecordDateTime" value="@Model.Records.ToList()[i].RecordDateTime" />
                </p>
            }
            <p>
                <input class="btn @Design.Color right" type="submit" value="@Localizer["CreatePDF"]" />
            </p>
        </form>
    </div>
</div>

TimeCardsApp/ETT.Client/Views/Record/UserList.cshtml
@model ETT.Web.Models.Record.RecordListViewModel

@{
    Layout = null;
}

<table class="col s12 bordered highlight">
    <thead>
        <tr>
            <th>Record ID</th>
            <th>User ID</th>
            <th>Project ID</th>
            <th>Task ID</th>
            <th>Note</th>
            <th>Work time</th>
            <th>Start date</th>
            <th class="right-align">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var record in Model.Records)
        {
            <tr>
                <td>
                    @record.Id
                </td>
                <td>
                    @record.UserId
                </td>
                <td>
                    @record.ProjectId
                </td>
                <td>
                    @record.TaskId
                </td>
                <td>
                    @record.Note
                </td>
                <td>
                    @record.Hours
                </td>
                <td>
                    @record.RecordDateTime
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@record.Id"><span class="new badge red darken-2" data-badge-caption="Delete"></span></a>
                    <a asp-action="Edit" asp-route-id="@record.Id"><span class="new badge orange darken-3" data-badge-caption="Edit"></span></a>
                </td>
            </tr>
        }
    </tbody>
</table>